Add auto-rendered product layout
Voog/design-sapporo pull request #222
Opened 2022-01-31 10:37 UTC by PeeterPaal

Closes #221

2022-02-03 16:12 UTC, tanelj requested changes
Nice work, but some comments.

* [x] Left side is too small for small screens when form content area is in right side:
![Screenshot 2022-02-03 at 18 08 29](https://user-images.githubusercontent.com/378755/152381324-31bed51b-8318-48c8-8010-f618a2e62a53.png)

2022-02-03 16:12 UTC, tanelj commented on layouts/auto_generated_product.tpl
> +{% include "template-variables" %}
Let's use white space strip here and below.

```suggestion
{%- include "template-variables" -%}
```

2022-02-03 16:12 UTC, tanelj commented on layouts/auto_generated_product.tpl
> +    {% capture bottom_content_html %}
Let's use white space strip.
```suggestion
    {%- capture bottom_content_html %}
```

2022-02-03 16:12 UTC, tanelj commented on layouts/auto_generated_product.tpl
> +                      </div>
Intent.

2022-02-03 16:12 UTC, tanelj commented on layouts/auto_generated_product.tpl
> +
Extra empy line.
```suggestion
```

2022-02-07 12:19 UTC, tanelj approved these changes
Nice!

2022-02-08 08:25 UTC, pxska requested changes
Cool! A few comments:

- [ ] The product description needs some space on the top if the viewport is small, otherwise the text is too close to the content on the right:
<img width="584" alt="Screenshot 2022-02-08 at 10 21 15" src="https://user-images.githubusercontent.com/48313701/152946486-179b7f3f-204a-444f-b93d-7956c6deff83.png">

- [ ] If you change the "maximum width" value from the design editor, the width changes, but the content-right stays the same width. It should increase in width like it does on the regular product page.

2022-02-08 08:25 UTC, pxska commented on sources/components/custom-styles/template-cs-product.scss
> +  #{--product-description-font-weight}: 400;
The `font-weight` value of text content areas on the page is `100` – maybe change the description's font-weight as well?

2022-02-09 09:36 UTC, pxska approved these changes
Looks good to me!

2022-02-10 11:40 UTC, tanelj requested changes
Nice and works, but one issue in Safari.

* [x] "Out of stock" button text is wrapped in Safari.
<img width="210" alt="Screenshot 2022-02-10 at 13 36 57" src="https://user-images.githubusercontent.com/378755/153401707-cf878230-c58d-4111-b54b-85f0033bef21.png">

2022-02-10 13:19 UTC, tanelj approved these changes

2022-02-10 20:19 UTC, merged